/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BettingTrend {
  'homeBetPercentage' : number,
  'matchup' : bigint,
  'awayBetPercentage' : number,
}
export interface ExpertPick {
  'pick' : string,
  'reasoning' : string,
  'matchup' : bigint,
  'confidencePercentage' : number,
}
export interface InjuryReport {
  'status' : string,
  'team' : string,
  'playerName' : string,
  'impactAnalysis' : string,
}
export interface Matchup {
  'homeTeam' : string,
  'league' : string,
  'awayTeam' : string,
  'sportsbookOdds' : Array<[string, Odds]>,
}
export interface Odds {
  'total' : number,
  'spread' : number,
  'moneyline' : number,
}
export interface TeamStats {
  'defenseRank' : bigint,
  'teamName' : string,
  'recentForm' : Array<number>,
  'yardsPerGame' : number,
  'pointsPerGame' : number,
}
export interface _SERVICE {
  'getAllBettingTrends' : ActorMethod<[], Array<BettingTrend>>,
  'getAllExpertPicks' : ActorMethod<[], Array<ExpertPick>>,
  'getAllInjuryReports' : ActorMethod<[], Array<InjuryReport>>,
  'getAllMatchups' : ActorMethod<[], Array<Matchup>>,
  'getAllTeamStats' : ActorMethod<[], Array<TeamStats>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];