/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BettingTrend = IDL.Record({
  'homeBetPercentage' : IDL.Float64,
  'matchup' : IDL.Nat,
  'awayBetPercentage' : IDL.Float64,
});
export const ExpertPick = IDL.Record({
  'pick' : IDL.Text,
  'reasoning' : IDL.Text,
  'matchup' : IDL.Nat,
  'confidencePercentage' : IDL.Float64,
});
export const InjuryReport = IDL.Record({
  'status' : IDL.Text,
  'team' : IDL.Text,
  'playerName' : IDL.Text,
  'impactAnalysis' : IDL.Text,
});
export const Odds = IDL.Record({
  'total' : IDL.Float64,
  'spread' : IDL.Float64,
  'moneyline' : IDL.Float64,
});
export const Matchup = IDL.Record({
  'homeTeam' : IDL.Text,
  'league' : IDL.Text,
  'awayTeam' : IDL.Text,
  'sportsbookOdds' : IDL.Vec(IDL.Tuple(IDL.Text, Odds)),
});
export const TeamStats = IDL.Record({
  'defenseRank' : IDL.Nat,
  'teamName' : IDL.Text,
  'recentForm' : IDL.Vec(IDL.Float64),
  'yardsPerGame' : IDL.Float64,
  'pointsPerGame' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllBettingTrends' : IDL.Func([], [IDL.Vec(BettingTrend)], ['query']),
  'getAllExpertPicks' : IDL.Func([], [IDL.Vec(ExpertPick)], ['query']),
  'getAllInjuryReports' : IDL.Func([], [IDL.Vec(InjuryReport)], ['query']),
  'getAllMatchups' : IDL.Func([], [IDL.Vec(Matchup)], ['query']),
  'getAllTeamStats' : IDL.Func([], [IDL.Vec(TeamStats)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BettingTrend = IDL.Record({
    'homeBetPercentage' : IDL.Float64,
    'matchup' : IDL.Nat,
    'awayBetPercentage' : IDL.Float64,
  });
  const ExpertPick = IDL.Record({
    'pick' : IDL.Text,
    'reasoning' : IDL.Text,
    'matchup' : IDL.Nat,
    'confidencePercentage' : IDL.Float64,
  });
  const InjuryReport = IDL.Record({
    'status' : IDL.Text,
    'team' : IDL.Text,
    'playerName' : IDL.Text,
    'impactAnalysis' : IDL.Text,
  });
  const Odds = IDL.Record({
    'total' : IDL.Float64,
    'spread' : IDL.Float64,
    'moneyline' : IDL.Float64,
  });
  const Matchup = IDL.Record({
    'homeTeam' : IDL.Text,
    'league' : IDL.Text,
    'awayTeam' : IDL.Text,
    'sportsbookOdds' : IDL.Vec(IDL.Tuple(IDL.Text, Odds)),
  });
  const TeamStats = IDL.Record({
    'defenseRank' : IDL.Nat,
    'teamName' : IDL.Text,
    'recentForm' : IDL.Vec(IDL.Float64),
    'yardsPerGame' : IDL.Float64,
    'pointsPerGame' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllBettingTrends' : IDL.Func([], [IDL.Vec(BettingTrend)], ['query']),
    'getAllExpertPicks' : IDL.Func([], [IDL.Vec(ExpertPick)], ['query']),
    'getAllInjuryReports' : IDL.Func([], [IDL.Vec(InjuryReport)], ['query']),
    'getAllMatchups' : IDL.Func([], [IDL.Vec(Matchup)], ['query']),
    'getAllTeamStats' : IDL.Func([], [IDL.Vec(TeamStats)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };